cs290-02-sp23-hw-hw7-hw7-goalmatic-sl706/config/routes.rb
Rails.application.routes.draw do
  resources :badges
  get 'home' => 'home#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  resources :users
  resources :categories
  resources :challenges do
    resources :activities
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

cs290-02-sp23-hw-hw7-hw7-goalmatic-sl706/app/models/challenge.rb
class Challenge < ApplicationRecord
  has_many :activities, dependent: :destroy
  has_many :badge_awards
  belongs_to :category
  belongs_to :user

  validates :name, presence: true

  def activity_created(activity)
    self.progress += activity.amount
    save
  end

  def activity_destroyed(activity)
    self.progress -= activity.amount
    save
  end
  
end

cs290-02-sp23-hw-hw7-hw7-goalmatic-sl706/app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :set_challenge, only: %i[ show edit update destroy ]

  # GET /challenges or /challenges.json
  def index
    @challenges = current_user.challenges
  end

  # GET /challenges/1 or /challenges/1.json
  def show
    @activities = @challenge.activities
  end

  # GET /challenges/new
  def new
    @challenge = Challenge.new
  end

  # GET /challenges/1/edit
  def edit
  end

  # POST /challenges or /challenges.json
  def create
    @challenge = current_user.challenges.new(challenge_params)

    respond_to do |format|
      if @challenge.save
        format.html { redirect_to challenge_url(@challenge), notice: "Challenge was successfully created." }
        format.json { render :show, status: :created, location: @challenge }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /challenges/1 or /challenges/1.json
  def update
    respond_to do |format|
      if @challenge.update(challenge_params)
        format.html { redirect_to challenge_url(@challenge), notice: "Challenge was successfully updated." }
        format.json { render :show, status: :ok, location: @challenge }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /challenges/1 or /challenges/1.json
  def destroy
    @challenge.destroy

    respond_to do |format|
      format.html { redirect_to challenges_url, notice: "Challenge was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_challenge
      @challenge = Challenge.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def challenge_params
      params.require(:challenge).permit(:name, :category_id, :goal, :units, :progress, :ends_at)
    end
end

cs290-02-sp23-hw-hw7-hw7-goalmatic-sl706/app/helpers/challenges_helper.rb
module ChallengesHelper
end

cs290-02-sp23-hw-hw7-hw7-goalmatic-sl706/app/views/challenges/_challenge.html.erb
<div id="<%= dom_id challenge %>">

  <p class="my-2">
    <%= challenge.category.name %>
  </p>

  <p class="my-2">
    <h1><%= challenge.name %></h1>
  </p>

  <p class="my-2">
    <strong class="font-medium mb-1">Ends at:</strong>
    <%= challenge.ends_at %>
  </p>

  <div class="container flex my-5">
    <div class="w-1/2 pr-4">
      <strong class="font-medium mb-1">Goal:</strong>
      <%= challenge.goal %>
      <%= challenge.units %>
    </div>

    <div class="w-1/2 pl-4">
      <strong class="font-medium mb-1">Progress:</strong>
      <%= challenge.progress %>
    </div>
  </div>

  <% if action_name != "show" %>
    <%= link_to "Show this challenge", challenge, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this challenge', edit_challenge_path(challenge), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

cs290-02-sp23-hw-hw7-hw7-goalmatic-sl706/app/views/challenges/_form.html.erb
<%= form_with(model: challenge, class: "contents") do |form| %>
  <% if challenge.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(challenge.errors.count, "error") %> prohibited this challenge from being saved:</h2>

      <ul>
        <% challenge.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.all, :id, :name, { prompt: true }, { class: "input-field" } %>
  </div>

  <div class="my-5">
    <%= form.label :goal %>
    <%= form.number_field :goal, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :units %>
    <%= form.text_field :units, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :progress %>
    <%= form.number_field :progress, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :ends_at %>
    <%= form.date_field :ends_at, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

cs290-02-sp23-hw-hw7-hw7-goalmatic-sl706/app/views/challenges/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing challenge</h1>

  <%= render "form", challenge: @challenge %>

  <%= link_to "Show this challenge", @challenge, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to challenges", challenges_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

cs290-02-sp23-hw-hw7-hw7-goalmatic-sl706/app/views/challenges/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Challenges</h1>
    <%= link_to 'New challenge', new_challenge_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="challenges" class="min-w-full">
    <% @challenges.each do |challenge| %>
      <%= link_to challenge.name, challenge, class: "block" %>
    <% end %>
  </div>
</div>

cs290-02-sp23-hw-hw7-hw7-goalmatic-sl706/app/views/challenges/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New challenge</h1>

  <%= render "form", challenge: @challenge %>

  <%= link_to 'Back to challenges', challenges_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

cs290-02-sp23-hw-hw7-hw7-goalmatic-sl706/app/views/challenges/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @challenge %>

  <h2 class="text-xl font-bold">
    Activities         
    <span class="ml-20">
      <%= link_to "Add an Activity", new_challenge_activity_path(@challenge) %>
    </span>
  </h2>

  <ul class="block">
    <% @activities.each do |activity| %>
      <%= render partial: 'activities/activity_listing', locals: { challenge: @challenge, activity: activity} %>
    <% end %>
  </ul>

    <%= link_to 'Edit this challenge', edit_challenge_path(@challenge), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this challenge', challenge_path(@challenge), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to challenges', challenges_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>