cs290-02-sp23-hw-hw7-hw7-goalmatic-sl706/config/routes.rb
Rails.application.routes.draw do
  resources :badges
  get 'home' => 'home#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  resources :users
  resources :categories
  resources :challenges do
    resources :activities
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

cs290-02-sp23-hw-hw7-hw7-goalmatic-sl706/app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :challenge
  belongs_to :user
  after_create :update_challenge_progress_after_create
  after_destroy :update_challenge_progress_after_destroy
  after_create :award_badges

  def award_badges
    BadgeAwardService.award_badges(self)
  end

  validates :amount, presence: true, numericality: { greater_than: 0 }

  def update_challenge_progress_after_create
    challenge.activity_created(self)
  end

  def update_challenge_progress_after_destroy
    challenge.activity_destroyed(self)
  end
  
end

cs290-02-sp23-hw-hw7-hw7-goalmatic-sl706/app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_challenge
  before_action :set_activity, only: %i[ show edit update destroy ]

  # GET /activities or /activities.json
  def index
    @activities = @challenge.activities
  end

  # GET /activities/1 or /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = @challenge.activities.build
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities or /activities.json
  def create
    @activity = @challenge.activities.build(activity_params)
    @activity.user = current_user

    respond_to do |format|
      if @activity.save
        format.html { redirect_to challenge_url(@challenge), notice: "Activity was successfully created." }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1 or /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to challenge_url(@challenge), notice: "Activity was successfully updated." }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1 or /activities/1.json
  def destroy
    @activity.destroy

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(helpers.dom_id(@activity).to_sym) }
      format.html { redirect_to challenge_url(@challenge), notice: "Activity was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = @challenge.activities.find(params[:id])
    end

    def set_challenge
      @challenge = Challenge.find(params[:challenge_id])
    end

    # Only allow a list of trusted parameters through.
    def activity_params
      params.require(:activity).permit(:note, :amount, :challenge_id)
    end
end

cs290-02-sp23-hw-hw7-hw7-goalmatic-sl706/app/helpers/activities_helper.rb
module ActivitiesHelper
end

cs290-02-sp23-hw-hw7-hw7-goalmatic-sl706/app/views/activities/_activity.html.erb
<div id="<%= dom_id activity %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Note:</strong>
    <%= activity.note %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Amount:</strong>
    <%= activity.amount %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Challenge:</strong>
    <%= activity.challenge.name %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this activity", challenge_activity_path(@challenge, activity), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this activity', edit_challenge_activity_path(@challenge, activity), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

cs290-02-sp23-hw-hw7-hw7-goalmatic-sl706/app/views/activities/_activity_listing.html.erb
<div class="block flex mt-3" id=<%= dom_id(activity)%>>

  <span class="mr-10">
    <%= link_to "#{activity.amount} #{activity.challenge.units}" , challenge_activity_path(@challenge, activity) %>
  </span>
  <%= activity.note %>
  <%= button_to "Delete",
    challenge_activity_path(challenge, activity),
    params: { activity: { id: activity.id }}, 
    method: :delete,
    form_class: "inline-block",
    class: "rounded-sm ml-5 py-1 px-2 bg-gray-100 inline-block font-small"
  %>
</div>

cs290-02-sp23-hw-hw7-hw7-goalmatic-sl706/app/views/activities/_form.html.erb
<%= form_with(model: [@challenge, activity], class: "contents") do |form| %>
  <% if activity.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% activity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :note %>
    <%= form.text_field :note, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :amount %>
    <%= form.number_field :amount, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :challenge_id %>
    <%= form.text_field :challenge_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

cs290-02-sp23-hw-hw7-hw7-goalmatic-sl706/app/views/activities/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing activity</h1>

  <%= render "form", activity: @activity %>

  <%= link_to "Show this activity", challenge_activity_path(@challenge, @activity), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to activities", challenge_activities_path(@challenge), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

cs290-02-sp23-hw-hw7-hw7-goalmatic-sl706/app/views/activities/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Activities</h1>
    <%= link_to 'New activity', new_challenge_activity_path(@challenge), class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="activities" class="min-w-full">
    <%= render @activities %>
  </div>
</div>

cs290-02-sp23-hw-hw7-hw7-goalmatic-sl706/app/views/activities/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New activity</h1>

  <%= render "form", activity: @activity %>

  <%= link_to 'Back to activities', challenge_activities_path(@challenge), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

cs290-02-sp23-hw-hw7-hw7-goalmatic-sl706/app/views/activities/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @activity %>

    <%= link_to 'Edit this activity', edit_challenge_activity_path(@challenge, @activity), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this activity', challenge_activity_path(@challenge, @activity), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to activities', challenge_activities_path(@challenge), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Back to the challenge', challenge_path(@challenge), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>