cs290-02-sp23-hw-hw7-hw7-goalmatic-sl706/config/routes.rb
Rails.application.routes.draw do
  resources :badges
  get 'home' => 'home#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  resources :users
  resources :categories
  resources :challenges do
    resources :activities
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

cs290-02-sp23-hw-hw7-hw7-goalmatic-sl706/app/models/badge.rb
class Badge < ApplicationRecord
  has_many :badge_awards, dependent: :destroy
  has_many :users, through: :badge_awards
  belongs_to :category, optional: true

  def goal
    @goal ||= goal_type? ? goal_type.constantize.new(self) : nil
  end

  def awardable?(activity)
    !awarded?(activity) && 
    goal.present? && 
    goal.achieved?(activity)
  end

  def awarded?(activity)
    BadgeAward.exists?(
      badge_id: id, 
      user_id: activity.user_id, 
      challenge_id: activity.challenge_id)
  end

end

cs290-02-sp23-hw-hw7-hw7-goalmatic-sl706/app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :set_badge, only: %i[ show edit update destroy ]

  # GET /badges or /badges.json
  def index
    @badges = Badge.all
  end

  # GET /badges/1 or /badges/1.json
  def show
  end

  # GET /badges/new
  def new
    @badge = Badge.new
  end

  # GET /badges/1/edit
  def edit
  end

  # POST /badges or /badges.json
  def create
    @badge = Badge.new(badge_params)

    respond_to do |format|
      if @badge.save
        format.html { redirect_to badge_url(@badge), notice: "Badge was successfully created." }
        format.json { render :show, status: :created, location: @badge }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /badges/1 or /badges/1.json
  def update
    respond_to do |format|
      if @badge.update(badge_params)
        format.html { redirect_to badge_url(@badge), notice: "Badge was successfully updated." }
        format.json { render :show, status: :ok, location: @badge }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /badges/1 or /badges/1.json
  def destroy
    @badge.destroy

    respond_to do |format|
      format.html { redirect_to badges_url, notice: "Badge was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_badge
      @badge = Badge.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def badge_params
      params.require(:badge).permit(:name, :description, :category_id, :count, :goal_type)
    end
end

cs290-02-sp23-hw-hw7-hw7-goalmatic-sl706/app/helpers/badges_helper.rb
module BadgesHelper
end

cs290-02-sp23-hw-hw7-hw7-goalmatic-sl706/app/views/badges/_badge.html.erb
<div id="<%= dom_id badge %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= badge.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= badge.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Category:</strong>
    <%= badge.category_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Count:</strong>
    <%= badge.count %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Goal type:</strong>
    <%= badge.goal_type %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this badge", badge, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this badge', edit_badge_path(badge), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

cs290-02-sp23-hw-hw7-hw7-goalmatic-sl706/app/views/badges/_form.html.erb
<%= form_with(model: badge, class: "contents") do |form| %>
  <% if badge.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(badge.errors.count, "error") %> prohibited this badge from being saved:</h2>

      <ul>
        <% badge.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_field :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
  <%= form.label :category_id %>
  <%= form.collection_select :category_id, Category.all, :id, :name, { prompt: true }, { class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" } %>
  </div>

  <div class="my-5">
    <%= form.label :count %>
    <%= form.number_field :count, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
  <%= form.label :goal_type %>
  <%= form.select :goal_type, options_for_select([["Double Your Progress", "BadgeGoals::DoubleProgressGoal"], ["Become Well Rounded", "BadgeGoals::WellRoundedGoal"]]), class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

cs290-02-sp23-hw-hw7-hw7-goalmatic-sl706/app/views/badges/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing badge</h1>

  <%= render "form", badge: @badge %>

  <%= link_to "Show this badge", @badge, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to badges", badges_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

cs290-02-sp23-hw-hw7-hw7-goalmatic-sl706/app/views/badges/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Badges</h1>
    <%= link_to 'New badge', new_badge_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="badges" class="min-w-full">
    <%= render @badges %>
  </div>
</div>

cs290-02-sp23-hw-hw7-hw7-goalmatic-sl706/app/views/badges/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New badge</h1>

  <%= render "form", badge: @badge %>

  <%= link_to 'Back to badges', badges_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

cs290-02-sp23-hw-hw7-hw7-goalmatic-sl706/app/views/badges/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @badge %>

    <%= link_to 'Edit this badge', edit_badge_path(@badge), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this badge', badge_path(@badge), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to badges', badges_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>